name: Build Clang (Ubuntu)

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1.8"

      - name: Install Dependencies
        #libtinfo5 not in the default 24.04 package repo
        run: |
          sudo apt update
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
          sudo apt install ./libtinfo5_6.3-2ubuntu0.1_amd64.deb
              
      - name: Build
        run: |
          cd Library
          premake5 gmake2
          premake5 build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-CSP
          path: ${{ github.workspace }}/Library/install/

  packaging_test:
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18.1.8"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-CSP
          path: PackagingTests/Cpp/install

      - name: Build
        run: |
          cd PackagingTests/Cpp
          premake5 gmake2
          make config=release

      - name: Run
        run: |
          cd bin/Release
          export LD_LIBRARY_PATH=$(pwd)/../install/lib
          ./CppPackagingTest

