name: Build MSVC (Windows)

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Enable long paths
        run: git config --system core.longpaths true

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '16.5'

      - name: Build on Windows
        run: |
          cd Library
          premake5 vs2022
          premake5 build

      - name: List contents of build directory
        run: |
          dir "${{ github.workspace }}/Library/build" --recurse
          dir "${{ github.workspace }}/Library/install"
          dir "${{ github.workspace }}/Library/install/bin"
          dir "${{ github.workspace }}/Library/install/bin" --recurse
        shell: pwsh

      - name: List contents of build directory (alt)
        run: |
          cmd /c tree /F
        shell: pwsh

      - name: List contents of build directory (alt2)
        run: |
          Get-ChildItem -Path ${{ github.workspace }} -Recurse | ForEach-Object { $_.FullName }
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-CSP
          path: ${{ github.workspace }}/Library/install/
